services:
  - type: web
    name: brandpulse-web
    env: docker
    plan: free
    branch: main
    autoDeploy: true
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        value: 'YOUR_JSON_STRING_HERE'
      - key: SPREADSHEET_ID
        value: 'YOUR_SPREADSHEET_ID_HERE'
      - key: OPENAI_API_KEY
        value: 'YOUR_OPENAI_API_KEY_HERE'
        
