services:
  - type: web
    name: brandpulse-blog-crawler
    env: docker
    plan: free
    envVars:
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        value: # (여기에 서비스 계정 JSON 전체를 한 줄로 입력하거나 Render 환경설정에서 관리)
      - key: OPENAI_API_KEY
        value: # (여기에 OpenAI API 키를 입력하거나 Render 환경설정에서 관리)
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /ms-playwright
