services:
  - type: web
    name: brandpulse-blog-crawler
    runtime: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    startCommand: "gunicorn --bind 0.0.0.0:$PORT blog:app"
