services:
  - type: worker
    name: brandpulse-blog
    env: docker
    plan: free
    repo: coin2watch/brandpulse-lottehotel
    branch: main
    autoDeploy: true
    envVars:
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        value: 'YOUR_JSON_STRING_HERE'
      - key: SPREADSHEET_ID
        value: 'YOUR_SPREADSHEET_ID_HERE'
