services:
  - type: web
    name: brandpulse-blog-crawler
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
    startCommand: python blog.py
    plan: free
