services:
  - type: web
    name: brandpulse-blog
    runtime: docker
    plan: free
    envVars:
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    dockerContext: .
    dockerfilePath: Dockerfile
    startCommand: gunicorn blog:app --bind 0.0.0.0:$PORT
