services:
  - type: web
    name: brandpulse-blog-crawler
    runtime: python
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.cache/ms-playwright
    buildCommand: |
      pip install -r requirements.txt
      playwright install
    startCommand: python blog.py
    plan: free
