services:
  - type: web
    name: brandpulse-web
    env: docker
    plan: free
    autoDeploy: true
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        value: 'YOUR_JSON_STRING'
      - key: SPREADSHEET_ID
        value: 'YOUR_SPREADSHEET_ID'
