services:
  - type: web
    name: brandpulse-blog-crawler
    env: docker
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        value: # (여기에 OpenAI API 키를 입력하거나 Render 환경설정에서 관리)
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /ms-playwright
    startCommand: gunicorn --workers=1 --timeout=120 blog:app
